"use client";

import { useState, useEffect } from "react";
import { useAuth } from "@/lib/auth-context";
import { api } from "@/lib/api";
import { toast } from "sonner";

interface Week {
  week: number;
  title: string;
  tasks: string[];
}

interface Roadmap {
  id: string;
  title: string;
  days: {
    title: string;
    weeks: Week[];
  };
  aiModel: string;
  generatedAt: string;
}

export default function RoadmapPage() {
  const { token } = useAuth();
  const [roadmap, setRoadmap] = useState<Roadmap | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);

  const fetchRoadmap = async () => {
    if (!token) return;
    setIsLoading(true);
    const response = await api.getRoadmap(token);

    if (response.success && response.data?.roadmap) {
      setRoadmap(response.data.roadmap as Roadmap);
    } else {
      setRoadmap(null);
    }
    setIsLoading(false);
  };

  const handleGenerate = async () => {
    if (!token) return;

    setIsGenerating(true);

    const response = await api.generateRoadmap(token);

    if (response.success && response.data?.roadmap) {
      setRoadmap(response.data.roadmap as Roadmap);
    } else {
      toast.error(response.error || "Failed to generate roadmap. Please ensure your business profile is complete.");
    }

    setIsGenerating(false);
  };

  useEffect(() => {
    fetchRoadmap();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [token]); // fetchRoadmap stable intent for token-driven data load

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  return (
    <div className="w-full max-w-4xl mx-auto px-3 sm:px-6 py-4 sm:py-6 overflow-x-hidden pb-24 md:pb-8">
      <div className="flex items-center justify-between gap-3 mb-5">
        <div>
          <h1 className="mm-page-title">30-Day Growth Roadmap</h1>
          <p className="mm-secondary mt-0.5">Personalized weekly action plan based on your business profile</p>
        </div>

        <button
          onClick={handleGenerate}
          disabled={isGenerating || isLoading}
          className="mm-btn mm-btn-primary focus-ring shrink-0"
        >
          {isGenerating ? "Generating..." : roadmap ? "Regenerate Roadmap" : "Generate Roadmap"}
        </button>
      </div>

      {isLoading ? (
        <div className="animate-pulse space-y-4">
          {/* Roadmap header skeleton */}
          <div className="h-24 mm-card" />
          {/* Week cards skeleton */}
          {[1, 2, 3, 4].map((i) => (
            <div key={i} className="h-40 mm-card" />
          ))}
        </div>
      ) : roadmap ? (
        <div className="space-y-4">
          {/* Header */}
          <div className="mm-card p-4 sm:p-5">
            <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3">
              <div>
                <h2 className="text-base font-semibold">{roadmap.title}</h2>
                <p className="mm-secondary mt-0.5">
                  Generated on {formatDate(roadmap.generatedAt)} • {roadmap.aiModel}
                </p>
              </div>
              <div className="text-[11px] px-2.5 py-0.5 bg-muted text-muted-foreground rounded-full w-fit border border-border">
                4 Weeks • 30 Days
              </div>
            </div>
          </div>

          {/* Weeks */}
          <div className="space-y-3">
            {roadmap.days?.weeks?.map((week: Week, index: number) => (
              <div key={index} className="mm-card p-4 sm:p-5">
                <div className="flex items-start justify-between gap-3 mb-3">
                  <div>
                    <div className="mm-secondary font-medium tracking-wider uppercase text-emerald-700 dark:text-emerald-400">Week {week.week}</div>
                    <h3 className="text-sm font-semibold mt-0.5">{week.title}</h3>
                  </div>
                  <div className="text-[11px] px-2 py-0.5 bg-muted text-muted-foreground rounded-md border border-border shrink-0">
                    Days {(week.week - 1) * 7 + 1}–{week.week * 7}
                  </div>
                </div>

                <ul className="grid grid-cols-1 md:grid-cols-2 gap-x-5 gap-y-1.5 mt-3">
                  {week.tasks.map((task: string, taskIndex: number) => (
                    <li key={taskIndex} className="flex gap-2 text-[13px] leading-relaxed text-foreground">
                      <span className="text-emerald-600 dark:text-emerald-400 mt-0.5 leading-none">→</span>
                      <span>{task}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>

          <div className="mm-secondary text-center pt-2">
            This roadmap is generated by AI based on your current business profile. Regenerate after making significant updates to your profile for the most relevant advice.
          </div>
        </div>
      ) : (
        <div className="mm-card p-6 sm:p-8 text-center">
          <div className="mx-auto w-10 h-10 bg-muted rounded-lg flex items-center justify-center mb-3">
            <span className="text-lg">🗺️</span>
          </div>
          <h3 className="text-base font-semibold mb-1.5">No Roadmap Yet</h3>
          <p className="mm-secondary max-w-md mx-auto mb-5">
            Generate your personalized 30-day growth roadmap. It will be broken down into 4 weekly focus areas with specific actionable tasks.
          </p>
          <button
            onClick={handleGenerate}
            disabled={isGenerating}
            className="mm-btn mm-btn-primary focus-ring"
          >
            {isGenerating ? "Generating Roadmap..." : "Generate 30-Day Roadmap"}
          </button>
          <p className="mm-secondary mt-4">
            Complete your Business Profile first for the best results.
          </p>
        </div>
      )}
    </div>
  );
}
